services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/data/

  app-scan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - sqlite3
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID
      - SEND_MESSAGE_TELEGRAM
      - CRON_JOB_SCHEDULE

  phpliteadmin:
    hostname: phpliteadmin
    container_name: phpliteadmin
    image: vtacquet/phpliteadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/data/
    environment:
      - TZ=Europe/Paris
      - PASSWORD=${PHP_LITE_ADMIN_PASSWORD}
      - LOCATION=/data/

volumes:
  db:
